import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Card from '../components/Card';

const Home: NextPage = () => {
	const cards = [
		{
			key: 'item-1',
			title: 'Documentation',
			description: 'Find in-depth information about Next.js features and API.',
			path: 'https://nextjs.org/docs',
		},
		{
			key: 'item-2',
			title: 'Tailwind',
			description: 'Learn more and get started with Tailwind ',
			path: 'https://tailwindcss.com/',
		},
		{
			key: 'item-3',
			title: 'Next and tailwind',
			description: 'How to confígure Next with Tailwind step-by-step',
			path: 'https://tailwindcss.com/docs/guides/nextjs',
		},
		{
			key: 'item-4',
			title: 'NextJS API',
			description: 'NextJs API and routes introduction',
			path: 'https://nextjs.org/docs/api-routes/introduction',
		},
		{
			key: 'item-5',
			title: 'NextJS v.12',
			description: "What's new in NextJS 12 and React 18. Middlewares and new compiler",
			path:
				'https://blog.logrocket.com/whats-new-next-js-12/#:~:text=With%20the%20new%20Rust%20compiler,times%20faster%20builds%20for%20production.',
		},
		{
			key: 'item-6',
			title: 'Deploy Next to Vercel',
			description: 'Instantly deploy your Next.js site to a public URL with Vercel.',
			path:
				'https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app',
		},
	];

	return (
		<div className='py-0 md:px-8 px-6'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='flex flex-col min-h-screen px-0 py-16 flex-1 justify-center items-center'>
				<h1 className='m-0 text-6xl text-center'>
					Welcome to{' '}
					<a href='https://nextjs.org' className='no-underline text-blue-700 hover:underline'>
						Next.js!
					</a>
					<div className='mt-4'>
						<Image src='/meetup-logo.png' aria-label='meetup logo' width='300' height='90'></Image>
					</div>
				</h1>

				<p className='md:mt-16 mt-10 mx-0 text-2xl text-center'>
					Get started by editing <code className='rounded-md p-3 bg-zinc-100 text-lg font-mono'>pages/index.tsx</code>
				</p>
				<br />
				<p className='max-w-2xl mt-2 md:mb-16 mb-10 text-xl text-center'>
					On the links down below you will find a lot more info about NextJS, Tailwind, configuration, pros with NextJS,
					deployment to Vercel etc.
				</p>

				<div className='flex items-center justify-center flex-wrap max-w-3xl'>
					{cards.map((item) => (
						<Card key={item.key} path={item.path} title={item.title} description={item.description} />
					))}
				</div>
			</main>

			<footer className='flex flex-1 py-8 px-0 border-t justify-center items-center'>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					className='flex justify-center items-center grow'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className='h-4 ml-2'>
						<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

export default Home;
