import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Card from '../components/Card';
import { useState } from 'react';
import Dialog from '../components/Dialog';
import QRCode from 'react-qr-code';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
	const router = useRouter();

	const [showDialog, setShowDialog] = useState(false);
	//get origin
	const origin = typeof window !== 'undefined' && window.location.origin ? window.location.origin : '';

	const cards = [
		{
			key: 'item-1',
			title: 'NextJS documentation',
			description: 'Find in-depth information about Next.js features and API.',
			path: 'https://nextjs.org/docs',
		},
		{
			key: 'item-2',
			title: 'Tailwind',
			description: 'Learn more and get started with Tailwind ',
			path: 'https://tailwindcss.com/',
		},
		{
			key: 'item-3',
			title: 'NextJS and tailwind',
			description: 'How to confígure Next with Tailwind step-by-step',
			path: 'https://tailwindcss.com/docs/guides/nextjs',
		},
		{
			key: 'item-4',
			title: 'NextJS API',
			description: 'NextJS API and routes introduction',
			path: 'https://nextjs.org/docs/api-routes/introduction',
		},
		{
			key: 'item-5',
			title: 'NextJS v.12',
			description: "What's new in NextJS 12 and React 18. Middlewares and new compiler",
			path:
				'https://blog.logrocket.com/whats-new-next-js-12/#:~:text=With%20the%20new%20Rust%20compiler,times%20faster%20builds%20for%20production.',
		},
		{
			key: 'item-6',
			title: 'Deploy Next to Vercel',
			description: 'Instantly deploy your Next.js site to a public URL with Vercel.',
			path:
				'https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app',
		},
		{
			key: 'item-7',
			title: 'Tailwind components',
			description: 'Open source Tailwind components from Flowbite.',
			path: 'https://flowbite.com/docs/getting-started/introduction/',
		},
		{
			key: 'item-8',
			title: 'Next vs React',
			description: 'Which Framework Is Better For your Front-end?',
			path: 'https://www.ideamotive.co/blog/nextjs-vs-react-which-javascript-framework-is-better-for-your-front-end',
		},
		{
			key: 'item-9',
			title: 'Github',
			description: "The source code of today's demo",
			path: 'https://github.com/donaldsha/MeetUp-Demo',
		},
	];

	return (
		<div className='py-0 md:px-8 px-6'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='flex flex-col min-h-screen px-0 py-16 flex-1 justify-center items-center'>
				<h1 className='m-0 text-6xl text-center'>
					Welcome to{' '}
					<a href='https://nextjs.org' className='no-underline text-blue-700 hover:underline'>
						Next.js!
					</a>
					<div className='mt-4'>
						<Image src='/meetup-logo.png' aria-label='meetup logo' width='300' height='90'></Image>
					</div>
				</h1>

				<p className='md:mt-16 mt-10 mx-0 text-2xl text-center'>
					Get started by editing <code className='rounded-md p-3 bg-zinc-100 text-lg font-mono'>pages/index.tsx</code>
				</p>
				<br />
				<p className='max-w-2xl mt-2 md:mb-16 mb-10 text-xl text-center'>
					On the links down below you will find a lot more info about NextJS, Tailwind, configuration, pros with NextJS,
					deployment to Vercel etc.
				</p>

				{/* <button
					className='py-2.5 px-5 mr-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700'
					onClick={() => setShowDialog(true)}
				>
					Show QR
				</button> */}

				<div className='flex items-center justify-center flex-wrap max-w-3xl'>
					{cards.map((item) => (
						<Card key={item.key} path={item.path} title={item.title} description={item.description} />
					))}
				</div>
				{/* <Dialog show={showDialog} title='Lenke til demo' close={() => setShowDialog(!showDialog)}>
					<div>
						<QRCode value={`${origin}${router.pathname}`} level='H' size={340}/>
					</div>
				</Dialog> */}
			</main>

			<footer className='flex flex-1 py-8 px-0 border-t justify-center items-center'>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					className='flex justify-center items-center grow'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className='h-4 ml-2'>
						<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

// Home.getInitialProps = async (context) => { //getServerSideProps
// 	const { pathname } = context;
// 	return {props: pathname}
// };
interface Props {
	props: { pathname: string };
}

export default Home;
